### ISSUE TITLE
New Sidebar Roller Button Expands Awkwardly

### ISSUE THREAD

**Issue by WesWedding** [mkscho63/sta#125]
**Describe the bug**
When trying to use the new roller button introduced in the recent patch, it's a little wonky in Windows Foundry v12 (and maybe other versions).

**To Reproduce**
1.  Create a brand new fresh STA world
2. Launch it
3. Click the button. 

**Expected behavior**
I expected buttons to lay out in a way that matched how buttons display with other sidebar tools.

**Screenshots**
![image](https://github.com/user-attachments/assets/73733e89-ce3c-4562-92cb-2e38a55b2b86)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: The Windows standalone app, not a browser.  Roughly equivalent to a recent version of Chrome. 
 - Version: 12 (Build 330)

**Additional context**
This is in a world using only the STA System and no mods or any content, for that matter.

**Comment by tokeidlom** [comment]
I chose this option from the three I could see:
1) Follow the normal button approach - Pros, it looks default, Cons, There is a lot of mouse movement involved to click, the roller takes focus from whatever you were on (scene controls etc)
2) Add two new buttons, one for each roll type, Pros, fast and easy to click to roll (I'd have used the spock hand icon for the 2nd icon), Cons, Uses 2 icon slots
3) What we have here, Pros, doesn't take focus from whatever option you are on, very short mouse movement required for a quick roll, Cons, doesn't look default.

Honestly I would be happy if it is changed to any of those options, I slightly preferred option 3 and implemented that, but, my second choice would be for two buttons instead of one... Whatever the community prefers.

**Comment by WesWedding** [comment]
I think number 3 is okay (I believe only the Tile tools have a list that is long enough to overlap), it's more the way its laid out is what my issue was created for.

What I mean is:
   1.  The ship icon sort of detaches from the grey square background.   I think it should remain there, like it is when it isn't expanded, so that it always looks like a button.
   2. The new icons appear and partially hang off the main button out in space rather than look like their own clickable button-ness with their own square buttony background.
   3. There is a 3rd icon, a white square with a dot in the middle of it, that is partially obscured by the top button.  Is that a button, too?

**Comment by tokeidlom** [comment]
Ok with this now Wes? Shall we close it?

**Comment by WesWedding** [comment]
Yeah, I think this has been taken care of!
