### ISSUE TITLE
[STA1] Cannot drag Starship Weapons onto Ship Actor sheets

### ISSUE THREAD

**Issue by LonePaladin** [mkscho63/sta#167]
I cannot drag Starship Weapons from the Compendium into a Starship actor sheet. When I tried to recreate one manually, it appears that there are data fields in the manually-created item that the Compendium entry lacks.

In this image, the one on the left is the Compendium entry, the one on the right is the one I made manually.

![image](https://github.com/user-attachments/assets/9a307413-a057-4196-a352-e43435eebb97)

**Comment by tokeidlom** [comment]
It would appear that you have the 2e starship sheet open instead of the 1e. Can you try changing the sheet to 2e and back again. Sometimes it seems to pick the wrong one when the system is first installed.

Instructions here: 
https://github.com/mkscho63/sta/wiki/1st-or-2nd-Edition-Star-Trek-Adventure-Rules

**Comment by LonePaladin** [comment]
Hm. I just ran an update, and apparently every attempt I made to drop a weapon on the ship was retroactively applied. It looks like the manual-entry method -- specifically, clicking the `+` on the ship sheet itself, rather than making a new item -- that was using the 2E sheet when I first posted, but now it's using 1E.

So it's working _NOW_, just not sure why it changed.
