### ISSUE TITLE
Ship Talent "Advanced Shields" not calculated

### ISSUE THREAD

**Issue by Lucitus80** [mkscho63/sta#44]
Hello, right now, it's not possible to use the talent "Advanced Shields" for starships. You should get a bonus of +5 to your shields, but that's nothing you can manually adjust. 
I already exporting the acteur, editing the JSON and import... that doesn't work.

**Comment by mkscho63** [comment]
I haven't added in manually updating shield values, but at least for this the shields SHOULD update when you add a Talent called Advanced Shields to the ship, due to this code.
![image](https://user-images.githubusercontent.com/9925376/126005635-5f24bfbd-7a74-4094-a908-bdd8d15c5f45.png)
Is this not functioning properly though? I'd like to add in some more customization for the shield values, but I haven't gotten that in yet, so this was a stopgap I implemented.

**Comment by Lucitus80** [comment]
Ok, works as intended
