### ISSUE TITLE
Extended task - image customisation

### ISSUE THREAD

**Issue by Ryach** [mkscho63/sta#49]
If you could, would be great to add image to extended task similar to how they are in character card:
![image](https://user-images.githubusercontent.com/6523648/140405522-25d3bc16-7751-4fda-9d97-58d7cad77d83.png)
right now they dont look so great on the list with other characters.

**Comment by MrNightwood** [comment]
Was going to write a feature request for this but it looks like this one's already here. I've worked around this by using a generic icon and editing the database file to assign it to one extended task actor, then duplicating that actor each time I need a new task. This works to make it look half decent in the actors list, but I would appreciate there being a button to change it properly so that it doesn't look out of place in the actors list without undue effort.

**Comment by tokeidlom** [comment]
I think extended tasks need a major rework in general, I will add this to the request list

**Comment by tokeidlom** [comment]
As a stopgap have hard coded the image icon into the sheet, it allows for easy customisation until the ET sheet can be revisited. Will be included in the next release so closing now.
