### ISSUE TITLE
Attempting to Create NPC with Attributes Lower Than 7 resets it to 7

### ISSUE THREAD

**Issue by Aceman67** [mkscho63/sta#80]
I'm trying to create NPCs with attributes lower than 7 (A Targ from the CRB, p340), but when I try and set any of the values below 7, the sheet resets it to 7. 

This wasn't an issue before the update to FVTT v10.

**Comment by rrautkor** [comment]
I just noticed the same thing. It's obviously helpful for players to have the values clamped in order to avoid accidentally entering invalid inputs, but there needs to be some way of overriding the default behavior.

A quick fix would be to check some sort of tag in the character name I've been using `[Minor]`, `[Notable]`, and `[Major]` to indicate NPC characters, but a simple `[NPC]` might do. Also the Child Characters options from the Player's Guide may result in a character having an Attribute under 7, so maybe a `[Child]` tag for that might be helpful as well.

A proper UI for additional character options would of course be nice, too. Some of the fields and the Reputation track at the top are quite unnecessary for NPCs.

**Comment by mkscho63** [comment]
Reopening because I must have accidentally hit close with comment before.

One idea I was mulling about was adding a system level Game Setting to just remove the attribute/discipline limits that are in place. This way the person running gets to decide what they prefer, using the tags that were added in with 1.1.10 or just turning that automation off entirely.

**Comment by MrNightwood** [comment]
Definitely in support of the option to remove the hard limits. I had edited the JS file myself in previous versions to remove the lower limit so that the option was available, and of course was no incentive for my players to "cheat" by giving themselves lowered stats. In my opinion the tags solution is more cumbersome than it needs to be, the simple and more elegant solution to me is just being allowed to remove the limitations in the first place and letting the GM be the arbiter of the rules.

**Comment by MattBridger777** [comment]
There are some creatures in some of the pre-written adventures, for instance the episode "Darkness" in "Strange New Worlds," that have attributes above 12. So having the ability to alter/ignore the min/max values would be nice.

**Comment by mkscho63** [comment]
Implementing a setting with the next release that will allow users to override these limits. Just go into system settings and select that you want to "Ignore normal Max/Min limits..." for whatever values you want that automation removed from. I'll get some screenshots up in a lil bit.

**Comment by mkscho63** [comment]
![image](https://github.com/mkscho63/sta/assets/9925376/5bc06c9f-dc38-41dd-8f98-0a1a2fae6f9f)
